
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,threadump
  endpoint:
    health:
      show-details: always

mongo:
  hosts:
    - localhost:27017
  database: test

resilience4j:
  circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 10
      minimumNumberOfCalls: 3
      permittedNumberOfCallsInHalfOpenState: 2
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 5s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
      recordExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.util.concurrent.TimeoutException
        - java.io.IOException
        - org.springframework.web.server.ResponseStatusException
      ignoreExceptions:
  instances:
    customerService:
      baseConfig: default
  retry:
    configs:
  bulkhead:
    configs: