
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,threadump
  endpoint:
    health:
      show-details: always

mongo:
  hosts:
    - localhost:27017
  database: test

resilience4j:
 circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 10
      minimumNumberOfCalls: 6
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 5s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
      recordExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.util.concurrent.TimeoutException
        - java.io.IOException
        - org.springframework.web.server.ResponseStatusException
      ignoreExceptions:
        - com.wellsfargo.reactive.starter.greenfieldreactiveapplicationstarter.error.BusinessException
  instances:
    customerService:
      baseConfig: default

resilience4j.retry:
  configs:
    default:
      maxRetryAttempts: 3
      waitDuration: 100
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.util.concurrent.TimeoutException
        - java.io.IOException
        - org.springframework.web.server.ResponseStatusException
      ignoreExceptions:
        - com.wellsfargo.reactive.starter.greenfieldreactiveapplicationstarter.error.BusinessException
  instances:
    customerService:
      baseConfig: default

resilience4j.bulkhead:
  configs:
    default:
      maxConcurrentCalls: 2
  instances:
    customerService:
      baseConfig: default

resilience4j.ratelimiter:
  configs:
    default:
      registerHealthIndicator: false
      limitForPeriod: 10
      limitRefreshPeriod: 1s
      timeoutDuration: 0
      eventConsumerBufferSize: 100
  instances:
    customerService:
      baseConfig: default
    accountService:
      limitForPeriod: 6
      limitRefreshPeriod: 500ms
      timeoutDuration: 3s