spring:
  autoconfigure:
    exclude:
     - org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration
     - org.springframework.boot.autoconfigure.data.mongo.MongoReactiveDataAutoConfiguration