management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,threadump
  endpoint:
    health:
      show-details: always

mongo:
  hosts:
    - localhost:27017
  database: test